public class bmwcars implements carspecifications,flyingspecificationinterface {
    public void wheel(){
      system.debug('the mrf wheels are used '); 
    }
    public void steering (){
        system.debug('the power steerring is used ');
    }
    public void enginee (){
        system.debug('the 4stroke is used ');
        
    }
     public void camera (){
        system.debug('the 360d camera is used ');
        
    }
    public void wings (){
        system.debug('the 2 flying wings are used ');
    }
}