public class mobilespecifications {
public string name='Oneplus';    
    public void display(){
        system.debug('The mobile is :'+name);
    }
    public string inches='7.5';
        public string color='black';
                public string  ram='6';
        public string rom='125';
    public void specifications(){
        system.debug('the display size  :'+inches);
        system.debug('the color of the mobile :'+color);
        system.debug('the RAM space  :'+ram);
system.debug('the ROM space is  :'+rom);
    }
    public void makingcalls(){
        system.debug('High security calls  ');
            }
    public void sendingmessages(){
system.debug('to send encrypted msgs ');
    }

    }